# Generated by Django 5.1 on 2024-08-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_voto_escolher_votos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolher',
            old_name='opcao',
            new_name='opcões',
        ),
    ]
