# Generated by Django 5.1 on 2024-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_opcao_escolher_opcões'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolher',
            options={'ordering': ['id'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcões',
            new_name='opcão_1',
        ),
        migrations.AddField(
            model_name='escolher',
            name='opcões_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escolher',
            name='opcões_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escolher',
            name='opcões_4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
