# Generated by Django 5.1 on 2024-08-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_escolher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolher',
            options={'ordering': ['id'], 'verbose_name': 'Opcões', 'verbose_name_plural': 'Opcões'},
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcões_2',
            new_name='opcão_2',
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcões_3',
            new_name='opcão_3',
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcões_4',
            new_name='opcão_4',
        ),
    ]
