# Generated by Django 5.1 on 2024-08-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_escolher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolher',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='app.pergunta'),
        ),
    ]
