# Generated by Django 5.1 on 2024-08-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_escolher_pergunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolher',
            old_name='opcão_1',
            new_name='opcao_1',
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcão_2',
            new_name='opcao_2',
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcão_3',
            new_name='opcao_3',
        ),
        migrations.RenameField(
            model_name='escolher',
            old_name='opcão_4',
            new_name='opcao_4',
        ),
    ]
