# Generated by Django 5.1 on 2024-08-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_opcão_1_escolher_opcao_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolher',
            old_name='opcao_1',
            new_name='opcoes',
        ),
        migrations.RemoveField(
            model_name='escolher',
            name='opcao_2',
        ),
        migrations.RemoveField(
            model_name='escolher',
            name='opcao_3',
        ),
        migrations.RemoveField(
            model_name='escolher',
            name='opcao_4',
        ),
    ]
